### ISSUE TITLE
Queryset and template

### ISSUE THREAD

**Issue by maciejurm** [nitely/django-infinite-scroll-pagination#6]
Hi, do you have example how to use this in templates?:)

This will work with chained queryset?

**Comment by nitely** [comment]
> Hi, do you have example how to use this in templates?:)

Hey, I do something similar to this:

```python
  {% for article in page %}
    <h1>{{ article.title }}</h1>
  {% endfor %}

  {% spaceless %}
    <ul class="paginator">
      <li>
        {% if page.next_pages_left == limit %}
           +
        {% endif %}
        {{ page.next_pages_left }} pages left
      </li>
      {% if page.prev_page %}
        <li>
          <a class="paginator-button"
            href="?p={{ page.prev_page }}"
          >{% trans "Prev" %} <i class="fa fa-chevron-left"></i></a>
        </li>
      {% endif %}
      {% if page.next_page %}
        <li>
          <a class="paginator-button"
            href="?p={{ page.next_page }}"
          >{% trans "Next" %} <i class="fa fa-chevron-right"></i></a>
        </li>
      {% endif %}
    </ul>
  {% endspaceless %}
```

The result is something like: `+100 pages left [<] [>]`. The view just returns `render(request, 'myapp/foobar.html', {'page': page})`. There is no mixin for CBV if that's what you are asking, although it should not be hard to create one.

> This will work with chained queryset?

It supports passing any queryset, as the regular django paginator. However, it does not support `order_by` because it applies it's own `order_by`. Be aware it applies a limit (i.e: `page[:per_page]`), so the resulting page/queryset can't be chained further, although there is a way, let me know if want me to explain how to do that (it's not pretty, thought).

**Comment by nitely** [comment]
```python
{% if page.has_next %}
  {% spaceless %}
    <ul class="paginator">
      <li>
        <a class="paginator-button"
          href="?{{ page_var }}={{ page.next_page_pk }}{{ extra_query }}{{ hashtag }}"
        >{% trans "Next" %} <i class="fa fa-chevron-right"></i></a>
      </li>
    </ul>
  {% endspaceless %}
{% endif %}
```
